- name: Start Container
  hosts: ec2
  become: true

  tasks:
  - name: Start Container
    docker_container:
      name: my_container
      image: my_image
      state: started
      ports:
        - "80:80"
